export interface FluidState {
  id: string;
  uiConfig: string; // The HTML/React code generated by Agent B
  dataContext: any; // The JSON data from Agent A
  timestamp: number;
}

export class HistoryManager {
  private stack: FluidState[] = [];
  private pointer: number = -1;

  constructor() {
    // Try to load from localStorage (optional for now)
  }

  push(state: FluidState) {
    // If we are in the middle of the stack, discard the future
    if (this.pointer < this.stack.length - 1) {
      this.stack = this.stack.slice(0, this.pointer + 1);
    }
    this.stack.push(state);
    this.pointer++;
  }

  reset(initialState: FluidState) {
    this.stack = [initialState];
    this.pointer = 0;
  }

  clear() {
    this.stack = [];
    this.pointer = -1;
  }

  getCurrent(): FluidState | null {
    if (this.pointer === -1) return null;
    return this.stack[this.pointer];
  }

  goBack(): FluidState | null {
    if (this.pointer > 0) {
      this.pointer--;
      return this.stack[this.pointer];
    }
    return null;
  }

  goForward(): FluidState | null {
    if (this.pointer < this.stack.length - 1) {
      this.pointer++;
      return this.stack[this.pointer];
    }
    return null;
  }

  canGoBack(): boolean {
    return this.pointer > 0;
  }

  canGoForward(): boolean {
    return this.pointer < this.stack.length - 1;
  }
}
