export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css'
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton, OrganizationSwitcher } from '@clerk/nextjs'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header className="flex justify-between items-center p-4 gap-4 h-16 bg-slate-900 text-white">
            <div className="font-bold text-xl">Foundation</div>
            <div className="flex gap-4 items-center">
              <nav className="flex gap-4 text-sm">
                <a href="/projects" className="hover:text-blue-400">Projects</a>
                <a href="/editor" className="hover:text-purple-400 font-bold border-b-2 border-purple-400">Fluid Editor</a>
              </nav>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <OrganizationSwitcher afterCreateOrganizationUrl="/projects" />
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
