export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css'
import 'katex/dist/katex.min.css'
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton, OrganizationSwitcher } from '@clerk/nextjs'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="h-screen w-screen overflow-hidden flex flex-col">
          <header className="flex-none flex justify-between items-center p-4 gap-4 h-16 bg-slate-900 text-white z-50">
            <div className="font-bold text-xl">Foundation</div>
            <div className="flex gap-4 items-center">

              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <main className="flex-1 overflow-hidden relative">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
